### ISSUE TITLE
Getting warning and a notice on the Products listing page when no booking settings are created for the product

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/show-booking-settings#3]
Getting a warning and a notice on the Products listing page when no booking settings are created for the product.

http://prntscr.com/ea7rob

**Comment by vishalck** [comment]
Fixed in #5 .

**Comment by galakhyati** [comment]
Fixed in 22493479b097a86b1cec312013f83016c81388f9. Hence closing the issue.
