### ISSUE TITLE
Warnings displayed on activating the plugin on localhost which has PHP7

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/show-booking-settings#4]
Warning: Missing argument 1 for bkap_booking_details::__construct(), called in /opt/lampp/htdocs/wordpress-booking/wp-content/plugins/show-booking-details/show-booking-details.php on line 126 and defined in /opt/lampp/htdocs/wordpress-booking/wp-content/plugins/show-booking-details/show-booking-details.php on line 19

Warning: Missing argument 2 for bkap_booking_details::__construct(), called in /opt/lampp/htdocs/wordpress-booking/wp-content/plugins/show-booking-details/show-booking-details.php on line 126 and defined in /opt/lampp/htdocs/wordpress-booking/wp-content/plugins/show-booking-details/show-booking-details.php on line 19

**Comment by vishalck** [comment]
Fixed in #5 .

**Comment by galakhyati** [comment]
Fixed in 22493479b097a86b1cec312013f83016c81388f9. Hence closing the issue.
